funmusicplace/mirlo

client/src/components/AudioWrapper.tsx, client/src/components/Player.tsx, src/routers/v1/tracks/{id}/stream/{segment}.ts, src/utils/ownership.ts
=> fix: prevent non-preview plays on the API

package.json, yarn.lock
=> chore: upgrade prisma

client/src/components/Home.tsx, client/src/components/ManageArtist/PostForm.tsx, client/src/components/common/SongTimeDisplay.tsx, client/src/translation/en.json, client/src/types/index.d.ts, package.json, prisma/migrations/20231015125231_add_post_tier_relation/migration.sql, prisma/schema.prisma, src/index.ts, src/routers/auth.ts, src/routers/v1/artists/{id}/feed.ts, src/routers/v1/posts/index.ts, src/utils/post.ts, test.docker-compose.yml, test/routers/artists/index.spec.ts, test/routers/artists/{id}.feed.spec.ts, test/utils.ts, yarn.lock
Also adds tests
To do with #119 #120
=> Building a feed of posts that can be spit out as RSS

client/src/i18n.ts
=> fix: enable french translation

README.md, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/ManageArtist/ArtistForm.tsx, client/src/components/ManageArtist/ManageArtist.tsx, client/src/components/ManageArtist/TrackGroupCard.tsx, client/src/components/Post/index.tsx, client/src/components/Profile/UserSupports.tsx, client/src/components/TrackGroup/TrackGroup.tsx, client/src/components/common/TrackList.tsx, client/src/index.tsx, client/src/types/index.d.ts, src/routers/v1/users/{userId}/artists/index.ts, src/routers/v1/users/{userId}/artists/{artistId}/index.ts, src/routers/v1/users/{userId}/testExistence.ts, src/routers/v1/users/{userId}/trackGroups/index.ts, src/utils/artist.ts, src/utils/trackGroup.ts
This should handle #131 #134 and #123
=> fix: urlSlug should be lowercase and fix album url

client/src/components/Artist/ArtistTrackGroup.tsx, src/routers/v1/artists/{id}/subscribe.ts, src/routers/v1/checkout/index.ts, src/routers/v1/trackGroups/{id}/purchase.ts, src/routers/v1/users/{userId}/stripe/connect.ts, src/utils/stripe.ts
=> fix: pass stripeAccountId around

src/routers/v1/artists/{id}/subscribe.ts, src/routers/v1/checkout/webhook.ts, src/routers/v1/trackGroups/{id}/download.ts, src/routers/v1/trackGroups/{id}/purchase.ts, src/routers/v1/users/{userId}/subscriptions/{subscriptionId}.ts, src/utils/artist.ts, src/utils/stripe.ts, src/utils/trackGroup.ts, src/utils/user.ts
Another attempt at fixing this
=> 129 pass stripe account id to other places

client/package.json, client/src/components/Header/Header.tsx, client/src/components/Header/Menu.tsx, client/src/components/ManageArtist/AlbumForm.tsx, client/src/components/ManageArtist/BulkTrackUpload.tsx, client/src/components/ManageArtist/BulkTrackUploadRow.tsx, client/src/components/ManageArtist/Manage.tsx, client/src/components/ManageArtist/ManageAlbumForm.tsx, client/src/components/ManageArtist/ManageArtistAlbums.tsx, client/src/components/ManageArtist/ManageArtistSubscriptionTiers.tsx, client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/components/ManageArtist/TrackGroupCard.tsx, client/src/components/common/Tooltip.tsx, client/src/i18n.ts, client/src/index.tsx, client/src/services/APIInstance.ts, client/src/translation/en.json, client/src/types/parse-audio-metadata.d.ts, client/src/utils/usePublicObjectById.ts, client/yarn.lock, emails/album-purchase-receipt/html.pug, emails/album-purchase-receipt/text.pug, prisma/migrations/20231025184928_mark_track_artist_as_coauthor/migration.sql, prisma/schema.prisma, src/index.ts, src/jobs/convert-audio.ts, src/routers/v1/jobs/index.ts, src/routers/v1/users/{userId}/tracks/{trackId}/audio.ts, src/utils/processTrackAudio.ts, src/utils/trackGroup.ts
=> feat: bulk upload of tracks

client/src/components/AudioWrapper.tsx, client/src/components/common/SongTimeDisplay.tsx
=> fix: scrubber now updates

client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/i18n.ts, client/src/translation/README.md, client/src/utils/useGetUserObjectById.ts
=> fix: don't load album from public endpoint

README.md, client/.env.example, client/package.json, client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/components/TrackGroup/PurchaseOrDownloadAlbumModal.tsx, client/src/components/TrackGroup/TrackGroup.tsx, client/src/i18n.ts, client/src/services/api.ts, client/src/types/index.d.ts, client/yarn.lock, package.json, src/auth/passport.ts, src/index.ts, src/routers/auth.ts, src/routers/v1/trackGroups/{id}/download.ts, src/routers/v1/users/{userId}/tracks/{trackId}/index.ts, src/utils/minio.ts, test/routers/trackGroups/{id}.spec.ts, tsconfig.json, yarn.lock
=> Various fixes

README.md, client/src/components/ManageArtist/BulkTrackUpload.tsx, client/src/components/ManageArtist/BulkTrackUploadRow.tsx, client/src/components/common/SongTimeDisplay.tsx, package.json, src/index.ts, src/jobs/convert-audio.ts, src/utils/minio.ts, src/utils/processTrackAudio.ts, src/utils/trackGroup.ts, test/routers/users/tracks/tracks.spec.ts, yarn.lock
To do with #167 
See notes on ticket for issue with streaming that this _doesn't_ fix. Basically this just refactors for formats to be handled by a loop and array.
=> fix: clean up streaming processing

client/src/components/ManageArtist/AlbumForm.tsx, client/src/components/ManageArtist/BulkTrackUpload.tsx, client/src/components/ManageArtist/ManageTrackRow.tsx, client/src/components/ManageArtist/ManageTrackTable.tsx, client/src/components/ManageArtist/UploadImage.tsx, client/src/translation/en.json, client/src/types/index.d.ts, client/src/utils/useJobStatusCheck.ts, src/routers/v1/users/{userId}/trackGroups/{trackGroupId}/cover.ts, src/routers/v1/users/{userId}/trackGroups/{trackGroupId}/index.ts, src/utils/ownership.ts, src/utils/processImages.ts
It now shows a loading spinner if it's still processing the image
=> fix: image uploading on album edit

client/src/components/Home.tsx, client/src/components/Login.tsx, client/src/components/ManageArtist/AlbumForm.tsx, client/src/components/ManageArtist/ManageArtistAlbums.tsx, client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/components/Releases.tsx, client/src/index.tsx, client/src/translation/en.json, src/routers/v1/users/{userId}/testExistence.ts, src/routers/v1/users/{userId}/trackGroups/index.ts
=> feat: rework new album flow

client/src/components/ManageArtist/AlbumForm.tsx, client/src/components/ManageArtist/ManageArtistAlbums.tsx, client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/components/ManageArtist/TrackGroupCard.tsx, client/src/components/Player.tsx, client/src/components/common/Button.tsx, client/src/translation/en.json, client/src/utils/tracks.ts, src/auth/passport.ts, src/routers/v1/users/{userId}/trackGroups/{trackGroupId}/index.ts, src/routers/v1/users/{userId}/tracks/{trackId}/index.ts, src/utils/trackGroup.ts, src/utils/tracks.ts
#170 This lets users delete unpublished unreleased albums.
=> feat: allow delete of trackGroups

client/src/App.tsx, client/src/components/Artist/ArtistAlbums.tsx, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/ManageArtist/ManageArtist.tsx, client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/components/Player.tsx, client/src/components/TrackGroup/TrackGroup.tsx
Various small fixes : 
Button sizes on smaller devices (notably too big for translations into languages with longer words)
Margins and paddings on smaller devices in various situations.
Flex elements are now flush in all situations.
Fixed a banner issue when not logged in.
=> Small fixes

client/src/App.tsx, client/src/components/Artist/Artist.tsx
Quick Fix, where there were different paddings on artist / manage artist page, mostly due to a little hack I did that's no longer useful.
=> No longer needed code caused discrepency between manage artist / artist.

client/src/App.tsx, client/src/components/ManageArtist/ManageArtistContainer.tsx, client/src/components/ManageArtist/ManageContainer.tsx
All in the title. Got confused by the new containers.
=> Previous fix caused issues on trackgroups and homepage. Corrected.

client/src/components/ManageArtist/BulkTrackUpload.tsx, client/src/components/ManageArtist/EditTrackRow.tsx, client/src/components/TrackGroup/TrackGroup.tsx, client/src/components/common/PublicTrackGroupListing.tsx, client/src/components/common/Tooltip.tsx, client/src/translation/en.json, src/routers/v1/users/{userId}/tracks/{trackId}/audio.ts
=> feat: add track updating

client/src/components/ManageArtist/BulkTrackUpload.tsx, client/src/components/ManageArtist/Manage.tsx, client/src/components/common/Box.tsx, client/src/styles.ts, client/src/translation/en.json, prisma/migrations/20231111002917_addincomingfilelocation/migration.sql, prisma/migrations/20231111022151_remove_file_location_clumn/migration.sql, src/jobs/convert-audio.ts, src/routers/v1/users/{userId}/stripe/connect.ts, src/routers/v1/users/{userId}/tracks/{trackId}/audio.ts, src/utils/processTrackAudio.ts
=> Delete track audio and add ability to edit stripe account

client/src/components/Artist/Artist.tsx, client/src/components/Artist/ArtistAlbums.tsx, client/src/components/Artist/ArtistSupport.tsx, client/src/components/TrackGroup/TrackGroup.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/Button.tsx, client/src/components/common/DropdownMenu.tsx, client/src/components/common/FollowArtist.tsx, client/src/components/common/HeaderDiv.tsx, client/src/components/common/IconButton.tsx, client/src/state/GlobalState.tsx, client/src/translation/en.json, client/src/types/index.d.ts, prisma/migrations/20231115211849_make_tier_mandatory_value/migration.sql, prisma/schema.prisma, src/index.ts, src/routers/v1/artists/{id}/index.ts, src/routers/v1/artists/{id}/unfollow.ts, src/routers/v1/users/{userId}/artists/{artistId}/subscriptionTiers/index.ts, src/routers/v1/users/{userId}/subscriptions/index.ts, src/utils/artist.ts
=> feat: allow users to follow an artist

client/src/components/Artist/ArtistSupportBox.tsx, client/src/components/TrackGroup/PurchaseOrDownloadAlbumModal.tsx, emails/artist-subscription-receipt/html.pug, emails/artist-subscription-receipt/subject.pug, emails/artist-subscription-receipt/text.pug, src/routers/v1/artists/{id}/subscribe.ts, src/utils/stripe.ts
=> feat: enable subscriptions without login

client/src/components/Artist/Artist.tsx, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Header/Header.tsx, client/src/components/Home.tsx, client/src/components/Player.tsx, client/src/components/TrackGroup/PurchaseOrDownloadAlbumModal.tsx, client/src/components/common/DownloadAlbumButton.tsx, client/src/components/common/LoopButton.tsx, client/src/components/common/PauseButton.tsx, client/src/components/common/PlayButton.tsx, client/src/components/common/PublicTrackGroupListing.tsx, client/src/components/common/TrackRow.tsx, client/src/components/common/TrackRowPlayControl.tsx
Players buttons had wrong behaviors on hover and depending on user stylings, they're now consistent and mainly adjust to white and dark theme.
=> Fixed player buttons being unlegible in some contexts.

client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Header/Header.tsx, client/src/components/Home.tsx, client/src/components/ManageArtist/ManageArtist.tsx, client/src/components/ManageArtist/ManageArtistAlbums.tsx, client/src/components/ManageArtist/ManageArtistContainer.tsx, client/src/components/ManageArtist/ManageArtistPosts.tsx, client/src/components/ManageArtist/ManageArtistSubscriptionTiers.tsx, client/src/components/ManageArtist/ManageSubscriptionTierBox.tsx, client/src/components/ManageArtist/TrackGroupCard.tsx, client/src/components/Profile/Collection/index.tsx, client/src/components/Profile/WishlistCollection.tsx, client/src/components/TrackGroup/TrackGroup.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/Button.tsx, client/src/components/common/DownloadAlbumButton.tsx, client/src/translation/en.json, src/config/sharp.ts
Fixes here and there to : 
Collection page
Wishlist page
Album page
Buttons
Background / Banner
Manage page
=> Various minor adjustments

client/src/App.tsx, client/src/components/Artist/Artist.tsx, client/src/components/Artist/ArtistAlbums.tsx, client/src/components/Artist/ArtistSupport.tsx, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Header/Header.tsx, client/src/components/Home.tsx, client/src/components/ManageArtist/Manage.tsx, client/src/components/ManageArtist/ManageArtist.tsx, client/src/components/ManageArtist/ManageArtistAlbums.tsx, client/src/components/ManageArtist/ManageArtistContainer.tsx, client/src/components/ManageArtist/ManageArtistPosts.tsx, client/src/components/ManageArtist/ManageArtistSubscriptionTiers.tsx, client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/components/Profile/Collection/index.tsx, client/src/components/Profile/ProfileContainer.tsx, client/src/components/Profile/WishlistCollection.tsx, client/src/components/Profile/index.tsx, client/src/components/Releases.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/Button.tsx, client/src/components/common/Modal.tsx, client/src/styles.ts
This is mostly to clean up manually adjusted side paddings and font-size, created variables instead so it's easier to tweak global paddings.
Also did some overall adjustments to improve legibility on mobile.
=> Code Clean Up

client/src/App.tsx, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Header/HeaderSearch.tsx, client/src/components/Header/Menu.tsx, client/src/components/Home.tsx, client/src/components/ManageArtist/ManageArtistContainer.tsx, client/src/components/ManageArtist/ManageArtistSubscriptionTiers.tsx, client/src/components/Player.tsx, client/src/components/Profile/Collection/index.tsx, client/src/components/Releases.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/PageHeader.tsx, client/src/components/common/Tabs.tsx
Adding font-size variables in different places to make text-sizes more consistent. Switched Release Page to a row of 4 albums. (Can be switched back if we want)
=> Some more adjustments to paddings and font-sizes for legibility.

client/src/components/Artist/ArtistAlbums.tsx, client/src/components/Artist/ArtistPosts.tsx, client/src/components/Artist/ArtistSupportBox.tsx, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Home.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/Box.tsx, client/src/components/common/HeaderDiv.tsx, client/src/styles.ts
Bunch of minor fixes and padding adjustments but they help a lot I think.
=> Padding adjustments and fixed "follow button" display

client/src/components/Header/Menu.tsx, client/src/components/TrackGroup/TrackGroup.tsx, client/src/components/common/ClickToPlayAlbum.tsx
Pause wasn't working with the album play button but now it does.
=> Fixes to the "big album play button" (it now works)

client/src/components/Artist/ArtistSupport.tsx, client/src/components/TrackGroup/TrackGroup.tsx, client/src/components/common/ClickToPlay.tsx, client/src/styles.ts
=> A Bunch of minor fixes

client/src/components/Artist/Avatar.tsx, client/src/components/ManageArtist/ArtistFormLinks.tsx, client/src/components/ManageArtist/ManageTrackRow.tsx, client/src/components/Player.tsx, client/src/components/TrackGroup/Buy.tsx, client/src/components/TrackGroup/TrackGroup.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/ClickToPlay.tsx, client/src/components/common/ClickToPlayAlbum.tsx, client/src/components/common/PlayButton.tsx, client/src/components/common/PlayControlButton.tsx, client/src/types/index.d.ts
=> fix: refactor and allow stalled tracks to be deleted

client/src/components/Artist/ArtistPosts.tsx, client/src/components/Artist/ArtistSupport.tsx, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Home.tsx, client/src/components/Releases.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/Box.tsx, client/src/components/common/ClickToPlay.tsx, client/src/components/common/HeaderDiv.tsx
Just made the little things that the code clean up broke work again without adding much. 
Play button styling is better now.
Artist header section has better paddings and reordered buttons to avoid clutter.
=> Adjustments to code rework

client/src/components/Header/Header.tsx, client/src/components/ManageArtist/ArtistFormLinks.tsx, client/src/components/Releases.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/Modal.tsx, client/src/styles.ts
These are the changes made to modal in the other PR.
=> Modal and UI fixes

client/public/pages/CookiePolicy.md, client/src/components/Home.tsx, client/src/components/common/MarkdownContent.tsx, client/src/components/pages/About.tsx, client/src/components/pages/FAQ.tsx, client/src/index.tsx
=> feat: add cookie policy

docker-compose.yml, render.yaml, src/auth/passport.ts, src/index.ts, src/jobs/clean-up-files.ts, src/jobs/daily-tasks.ts, src/routers/v1/admin/tasks.ts, src/routers/v1/users/{userId}/artists/{artistId}/banner.ts, src/routers/v1/users/{userId}/tracks/{trackId}/audio.ts, src/utils/processTrackAudio.ts, test.docker-compose.yml, test/jobs/clean-up-files.spec.ts, test/routers/admin/tasks.spec.ts
=> feat: add endpoint for running tasks on the server

client/src/App.tsx, client/src/components/Artist/ArtistPosts.tsx, client/src/components/Artist/ArtistSupportBox.tsx, client/src/components/Home.tsx, client/src/components/Profile/ProfileContainer.tsx, client/src/components/Releases.tsx, client/src/components/common/Box.tsx, client/src/components/common/Overlay.tsx, client/src/components/common/PostCard.tsx, client/src/components/common/Table.tsx, client/src/styles.ts
Basically made them component, created an additional overlay component, and reworked Home and Artist pages so that they work with the new component.
=> Refactor of artist postcard in Home View and Artist View

client/src/components/Home.tsx, client/src/components/TrackGroup/TrackGroup.tsx
Forgot to add that bit of code when doing the width container
=> Fixed album page had no paddings on mobile view

client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Home.tsx, client/src/components/TrackGroup/PurchaseOrDownloadAlbumModal.tsx, client/src/components/common/ClickToPlay.tsx, client/src/components/common/DownloadAlbumButton.tsx, client/src/components/common/PlayingMusicBars.tsx, client/src/translation/en.json
Now the albums on hover have buy / wishlist / play options, but you can also go to album page by clicking the cover.
=> Refactor of ClickToPlay, makes albums clickable

client/src/components/common/ClickToPlay.tsx, client/src/components/common/PlayingMusicBars.tsx
=> Fix collision between music bars and go to album

client/src/components/common/ClickToPlay.tsx
Fixing all the tiny stuff I couldn't do yesterday
=> Centers wishlist icon

client/src/components/Header/Menu.tsx, client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/components/ManageArtist/Welcome.tsx, client/src/components/common/Button.tsx, client/src/components/common/PlatformPercent.tsx, client/src/components/common/Tooltip.tsx, client/src/translation/en.json, src/utils/artist.ts
=> fix: some more tweaks to artist and album edit pages

client/src/components/Header/Header.tsx, client/src/components/Home.tsx, client/src/components/ManageArtist/ManageArtistContainer.tsx, client/src/components/Releases.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/DropdownMenu.tsx, client/src/components/common/PageHeader.tsx, client/src/styles.ts
=> Hide header on scrolldown, show on scrollup

client/src/components/common/MetaCard.tsx
to do with https://github.com/nfl/react-helmet/issues/342
closes #379
=> fix: helmet build error with fragments

client/src/components/AudioWrapper.tsx, client/src/components/Player/index.tsx, client/src/components/Widget/TrackWidget.tsx, client/src/components/common/SongTimeDisplay.tsx
I'll try some styling on widget
=> Changed to have correct play button

client/src/components/Widget/TrackWidget.tsx, client/src/components/common/SmallTileDetails.tsx
=> fix to play pause button in widget

client/src/components/Header/Header.tsx, client/src/styles.ts
It didn't display properly on mobile because it assumed it had a banner.
=> Fix to the header scroll behavior on album page.

client/src/components/Widget/TrackWidget.tsx, client/src/components/common/SmallTileDetails.tsx
This should work with the proper behavior
=> Actual fix to widget

client/src/components/ManageArtist/ManageArtistPosts.tsx, client/src/components/ManageArtist/PostForm.tsx, client/src/components/Post/index.tsx, client/src/components/TrackGroup/ReleaseDate.tsx, client/src/translation/en.json, client/src/types/index.d.ts, src/routers/v1/posts/{id}.ts, src/routers/v1/users/{userId}/posts/index.ts, src/routers/v1/users/{userId}/tracks/{trackId}/audio.ts, src/utils/artist.ts, src/utils/post.ts, test/routers/posts/{id}.spec.ts, test/utils.ts
=> Post Content Fixes

client/src/components/Home.tsx
It displayed too light in light mode.
=> Color of mailing list button doesn't depend from dark/light mode.

client/src/components/Signup.tsx
Added name tags so that it becomes easy for the user
=> Fixed Issue #432

client/src/App.tsx, client/src/components/Artist/Artist.tsx, client/src/components/Artist/ArtistHeaderDescription.tsx, client/src/components/Artist/ArtistSupport.tsx, client/src/components/Footer.tsx, client/src/components/Header/Header.tsx, client/src/components/Header/HeaderSearch.tsx, client/src/components/ManageArtist/AlbumForm.tsx, client/src/components/ManageArtist/ArtistFormLinks.tsx, client/src/components/ManageArtist/ArtistFormLocation.tsx, client/src/components/ManageArtist/Manage.tsx, client/src/components/ManageArtist/ManageArtist.tsx, client/src/components/ManageArtist/ManageArtistSubscriptionTiers.tsx, client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/components/ManageArtist/ManageTrackRow.tsx, client/src/components/ManageArtist/ManageTrackTable.tsx, client/src/components/ManageArtist/PublishButton.tsx, client/src/components/ManageArtist/UploadArtistImage.tsx, client/src/components/TrackGroup/BuyTrackGroup.tsx, client/src/components/TrackGroup/TrackGroupTitle.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/Background.tsx, client/src/components/common/Button.tsx, client/src/components/common/DownloadAlbumButton.tsx, client/src/components/common/DropdownMenu.tsx, client/src/components/common/HeaderDiv.tsx, client/src/components/common/Modal.tsx, client/src/components/common/Tabs.tsx, client/src/components/common/Tooltip.tsx
Mostly adjustments to how the artist page is now setup with the tabs.
A new "big" button variant to create more differences between different roles in different contexts.
=> Adjustments new artist page

client/src/App.tsx, client/src/components/Footer.tsx, client/src/components/Header/Header.tsx, client/src/components/Header/LogInPopup.tsx, client/src/components/Home/Home.tsx, client/src/components/Home/HomeReleases.tsx, client/src/components/Home/Splash.tsx, client/src/components/Home/SupportMirlo.tsx, client/src/components/Login.tsx, client/src/components/ManageArtist/ManageArtistContainer.tsx, client/src/components/Widget/TrackWidget.tsx, client/src/components/common/LogInForm.tsx, client/src/components/common/Modal.tsx, client/src/styles.ts, client/src/translation/en.json
Lots of Tweaks to the UI to match new splash page and also to fix modal UI and make it more consistent all across the app
=> UI tweaks to new layout

client/src/components/Artist/ArtistAlbums.tsx, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Artist/ArtistVariableSupport.tsx, client/src/components/Home/HomeReleases.tsx, client/src/components/ManageArtist/TrackGroupCard.tsx, client/src/components/Profile/Collection/index.tsx, client/src/components/Profile/WishlistCollection.tsx, client/src/components/Releases.tsx, client/src/components/common/Button.tsx, client/src/components/common/TrackgroupGrid.tsx
Highly improved code for album grid, makes much more sense, is more legible but most importantly you can now toggle "3 row" or "4 row" with a variable which I think might be cool if we actually offered that as an option to artists to display one or the other option on their artist page. Now easily doable.
The rest is just small readability improvement tweaks to buttons on mobile and some more code cleanup.
=> Album grid improvement

client/src/components/Artist/ArtistPosts.tsx, client/src/components/Artist/ArtistSupport.tsx, client/src/components/Artist/ArtistSupportBox.tsx, client/src/components/Home/Posts.tsx
Same thinking than for the albumgrid rework, simplified code for readability and flexibility.
=> Postcard grid rework

client/src/components/Widget/TrackWidget.tsx, client/src/components/common/MarkdownContent.tsx, client/src/components/common/SmallTileDetails.tsx
Redone to avoid conflicts with main
=> Widget Bugfix

client/src/components/ManageArtist/Supporters.tsx, client/src/components/common/Table.tsx
Thought I'd fixed it, now I've fixed it.
=> Tables don't break with overflow on mobile anymore

client/src/components/Home/HomeReleases.tsx, client/src/components/ManageArtist/NewReleaseRedirect.tsx, src/auth/passport.ts, src/routers/v1/users/{userId}/artists/{artistId}/index.ts, src/routers/v1/users/{userId}/trackGroups/index.ts, src/routers/v1/users/{userId}/trackGroups/{trackGroupId}/index.ts, test/routers/users/artists/{id}.spec.ts, test/routers/users/trackGroups/index.spec.ts, test/routers/users/trackGroups/{id}.spec.ts
=> a couple of errors around user artists

client/src/components/Artist/ArtistSupportBox.tsx
When I fixed it earlier I applied the padding twice in two locations. My bad, corrected.
=> Somehow fixed the same thing twice, corrected that.

client/src/components/TrackGroup/TrackGroup.tsx
Remaking the PR with the new system based on reviews
=> Album page no credit or no about

client/src/components/ManageArtist/TrackGroupCard.tsx, client/src/components/common/Button.tsx, client/src/components/common/DropdownMenu.tsx, client/src/components/common/SupportArtistPopUp.tsx
Fix to dropdown menu list bullets
Fix to manage track card (changed buttons, made sure album is always displayed with a 1/1 ratio)
Fix to support button (added option for potentially long button names to have a wrap)
=> Fix dropdown menu list

client/src/components/common/DropdownMenu.tsx
=> Removed wrong padding

client/src/components/Widget/TrackWidget.tsx, client/src/components/common/MarkdownContent.tsx
Quick fix to height of track widget (was based on embeded in Mirlo)
=> Quick Fix to Track Widget Player

client/src/components/Widget/DisplayAudio.tsx, client/src/components/Widget/TrackGroupWidget.tsx, client/src/components/Widget/TrackWidget.tsx, client/src/components/Widget/utils.ts, client/src/components/common/MarkdownContent.tsx
Made a custom scrollbar for trackgroup widget so that it's more obvious that you need to scroll to see more on mobile
Improved track widget a lot to have a better management of space and better responsivness
=> Further widget tweaks

client/src/components/Widget/TrackWidget.tsx
Small tweak to album cover border radius
=> Border radius only where needed

client/src/components/Widget/TrackWidget.tsx, client/src/components/Widget/utils.ts
Really just a nitpick but it'll look better
=> Some margin/radius stuff

client/src/components/Player/VolumeControl.tsx, client/src/components/Player/index.tsx, client/src/components/common/Button.tsx, client/src/components/common/ClickToPlay.tsx, client/src/components/common/PlayButton.tsx, client/src/components/common/PlayControlButton.tsx
Fixed some buttons visual stuff that broke with recent updates
=> Fix to buttons

client/src/components/TrackGroup/TrackGroup.tsx, client/src/components/TrackGroup/TrackGroupEmbed.tsx, client/src/components/TrackGroup/TrackGroupTitle.tsx, client/src/components/TrackGroup/Wishlist.tsx
Now you can "share" right from underneath album image
=> Made "share" link more proeminent on album page

client/src/components/ManageArtist/ArtistSubscriberUploadData.tsx, client/src/components/TrackGroup/AddToCollection.tsx, client/src/components/common/DownloadAlbumButton.tsx, client/src/translation/en.json, docker-compose.yml, src/jobs/generate-album.ts, src/queues/album-queue.ts, src/routers/v1/trackGroups/{id}/download.ts
=> fix: attempt to fix download filename bug

client/src/components/Artist/ArtistSupportBox.tsx, client/src/components/Home/HomeReleases.tsx
=> fix: don't flex paragraphs display

client/src/components/ManageArtist/AlbumFormComponents/AlbumFormContent.tsx, client/src/components/ManageArtist/ArtistForm.tsx, client/src/components/ManageArtist/ColorInput.tsx, client/src/components/ManageArtist/ManageArtist.tsx, client/src/components/ManageArtist/ManageArtistAlbums.tsx, client/src/components/ManageArtist/PostForm.tsx, client/src/components/ManageArtist/UploadArtistImage.tsx, client/src/components/Profile/UserSupports.tsx, client/src/components/Profile/index.tsx, client/src/components/common/FormComponent.tsx, client/src/components/common/MarkdownWrapper.tsx
Cleaned up labels (some things were tagged labels, some others not, some were tagged twice within and outside of components etc.) and made sure they display with consistency across all form sections. 
Will look better and be much easier to style across the whole app later on (styling happens in form component)
=> made css labels consistent across sections

client/src/components/ManageArtist/ArtistSubscriberUploadData.tsx, client/src/components/TrackGroup/BuyTrackGroup.tsx, client/src/components/common/Input.tsx, client/src/components/common/TextArea.tsx, client/src/translation/en.json, emails/album-purchase-artist-notification/subject.pug, emails/new-user/subject.pug, src/utils/stripe.ts, src/utils/subscriptionTier.ts
=> Small bugs and adding tarckgroup

client/src/components/ManageArtist/ManageTrackRow.tsx, client/src/components/Widget/PlayButtonsWrapper.tsx
Play/Pause button was a little off when you hit play in the widget and in track rows
=> Fixed playbutton bad behavior

client/src/services/APIInstance.ts, client/src/state/ArtistContext.tsx, client/src/utils/useArtistColors.ts
This appears to fix the issue described in #629 - although I'm not sure if the same behavior occurs on any other routes.
=> Add AbortController to avoid fetch calls returning after page navigation

client/src/components/Home/Features.tsx
Removed "classname reverse" on the two features where it was because it broke the layout on mobile
=> Feature adjustment on mobile

.husky/pre-commit, .prettierignore, .prettierrc, client/src/App.test.tsx, client/src/App.tsx, client/src/components/Admin/TrackDetails.tsx, client/src/components/Artist/Artist.tsx, client/src/components/ErrorPage.tsx, client/src/components/ManageArtist/ArtistSubscriberUploadData.tsx, client/src/components/ManageArtist/ShowAlbumCodes.tsx, client/src/components/ManageArtist/UploadArtistImage.tsx, client/src/components/ManageArtist/utils.ts, client/src/components/Widget/utils.ts, client/src/components/common/Button.tsx, client/src/components/common/Snackbar.tsx, client/src/index.css, client/src/reportWebVitals.ts, client/src/services/APIInstance.ts, client/src/setupTests.ts, client/src/state/ArtistContext.tsx, client/tsconfig.json, package.json, src/jobs/generate-album.ts, yarn.lock
- Adds prettier config & dependencies to the root project
- Reformats a few files that didn't match the prettier formatting
- Adds `npx --no-install lint-staged` to the husky/pre-commit hook to format staged files on commit
(restricted to file types in `js,ts,jsx,tsx,json`)
=> Pre-commit hook / prettier config

client/src/components/Footer.tsx, client/src/components/Header/Header.tsx, client/src/components/Header/LogInPopup.tsx, client/src/components/common/ClickToPlay.tsx, client/src/styles.ts, client/src/translation/en.json
- Adds unique aria-labels to the social links on the homepage
- Adds a label to the "log in" button
- Adds a label to the "Mirlo" logo/link, and makes the image aria-hidden
- Fixes a z-index issue caused by #699 on the releases cards
=> Homepage button labels

client/src/components/Home/Kickstarter.tsx
Very minor but it'll look better on mobile, and since there's no way to hide it, I think it needs to be less intrusive to not impair the overall experience on Mirlo
=> Revised Kickstarter Strip to be less intrusive

client/src/components/common/Input.tsx
Probably messed that up with my ArtistForm refactor this week end sorry about that.
=> Bug in dark mode with input field

client/src/components/Artist/ArtistSupportBox.tsx, client/src/components/ManageArtist/AlbumFormComponents/AlbumFormContent.tsx, client/src/components/ManageArtist/ArtistForm.tsx, client/src/components/ManageArtist/UploadArtistImage.tsx, client/src/components/ManageArtist/Welcome.tsx, client/src/translation/en.json, src/jobs/optimize-image.ts, src/routers/v1/users/{userId}/artists/{artistId}/avatar.ts, src/routers/v1/users/{userId}/artists/{artistId}/banner.ts, src/routers/v1/users/{userId}/trackGroups/{trackGroupId}/cover.ts
Image uploads were limited to 4mb, which was cutting off a lot of pngs
=> Attempt to fix png upload

client/src/components/common/AutoComplete.tsx
=> fix: make autocomplete slightly better for if a new thing is allowed

src/auth/passport.ts, src/routers/v1/manage/trackGroups/{trackGroupId}/codes.ts, src/routers/v1/manage/trackGroups/{trackGroupId}/cover.ts, src/routers/v1/manage/trackGroups/{trackGroupId}/index.ts, src/routers/v1/manage/trackGroups/{trackGroupId}/publish.ts, src/routers/v1/manage/trackGroups/{trackGroupId}/tags.ts, src/routers/v1/manage/trackGroups/{trackGroupId}/trackOrder.ts, src/routers/v1/manage/tracks/index.ts, src/routers/v1/manage/tracks/{trackId}/audio.ts, src/routers/v1/manage/tracks/{trackId}/index.ts, src/routers/v1/manage/tracks/{trackId}/trackArtists.ts, src/routers/v1/trackGroups/{id}/download.ts, src/routers/v1/trackGroups/{id}/generateDownload.ts, src/routers/v1/tracks/{id}/stream/{segment}.ts, src/utils/ownership.ts, src/utils/trackGroup.ts
=> feat: refactor some admin editng thngs

client/src/components/common/Button.tsx
This _seems_ to solve it?
Closes #796
=> Wrap button text even if no spaces

client/src/translation/en.json
When talking about posts on an artist page, changed instances of "update" with "post"
Added points at the end of sentences
Replaced "musician" with "artist"
=> Vocabulary and typos

client/src/components/Admin/AdminLicenses.tsx, client/src/components/Home/Posts.tsx, client/src/components/ManageArtist/EditTrackRow.tsx, client/src/components/ManageArtist/ManageTrackLicense.tsx, client/src/components/common/LicenseForm.tsx, client/src/components/common/Modal.tsx, client/src/components/common/TrackRow.tsx, client/src/queries/licenses.ts, client/src/routes.tsx, client/src/translation/en.json, client/src/types/index.d.ts, prisma/migrations/20240814125034_/migration.sql, prisma/migrations/20240814174502_add_unique_constraint_to_license/migration.sql, prisma/migrations/20240814194029_add_name_to_license/migration.sql, prisma/schema.prisma, src/index.ts, src/routers/v1/admin/subscriptions.ts, src/routers/v1/licenses/index.ts, src/routers/v1/manage/tracks/{trackId}/index.ts, src/utils/trackGroup.ts, test/routers/admin/tasks.spec.ts, test/routers/manage/artists/{id}.trackgroups.spec.ts, test/routers/trackGroups/index.spec.ts, test/routers/trackGroups/{id}.redeemCode.spec.ts, test/utils.ts
=> feat: punt license feature

client/src/components/common/TrackRow.tsx
Closes https://github.com/funmusicplace/mirlo/issues/798
=> Pause play button offset left on mobile

client/src/components/Admin/AdminPurchases.tsx, client/src/components/common/Money.tsx, client/src/components/common/PlatformPercent.tsx, client/src/components/common/SupportArtistPopUpTiers.tsx, client/src/components/common/TipArtist.tsx, client/src/components/common/TipArtistForm.tsx, src/routers/v1/trackGroups/{id}/download.ts
=> fix: make currency not optional

client/src/components/Artist/ArtistPosts.tsx, client/src/components/ManageArtist/ArtistSlugInput.tsx, client/src/components/ManageArtist/Manage.tsx, client/src/components/ManageArtist/Merch/DeleteMerchButton.tsx, client/src/components/ManageArtist/Merch/EditMerch.tsx, client/src/components/ManageArtist/Merch/MerchDestinations.tsx, client/src/components/ManageArtist/Merch/MerchForm.tsx, client/src/components/ManageArtist/Merch/SelectTrackGroup.tsx, client/src/components/ManageArtist/UploadImage.tsx, client/src/components/ManageArtist/Welcome.tsx, client/src/components/Merch/MerchView.tsx, client/src/components/Post/PostCard.tsx, client/src/components/Post/PostGrid.tsx, client/src/components/Profile/UserNotificationFeed/NewArtistPost.tsx, client/src/components/common/AutoComplete.tsx, client/src/components/common/AutoCompleteTrackGroup.tsx, client/src/components/common/TextEditor/InsertMirloWidgetButton.tsx, client/src/queries/merch.ts, client/src/queries/queryKeys.ts, client/src/routes.tsx, client/src/translation/en.json, client/src/types/index.d.ts, prisma/schema.prisma, src/routers/v1/manage/artists/{artistId}/index.ts, src/routers/v1/manage/merch/{merchId}/index.ts, src/routers/v1/merch/{id}/index.ts, src/utils/artist.ts, src/utils/merch.ts, src/utils/stripe.ts, src/utils/trackGroup.ts
=> Linking trackgroups to merch and various other features

src/jobs/generate-album.ts, src/utils/trackGroup.ts
Includes the 1500 pixel cover image as "cover.jpg" in the zip file when downloading.
Closes #645
=> Include coverart in downloads

src/jobs/tasks/clean-up-files.ts
To do this, run the "cleanUpFiles" server task with jobParam "trackgroup-format".
=> Add param to remove objects from the trackgroup-format bucket.

src/routers/v1/trackGroups/{id}/download.ts, src/utils/trackGroup.ts
Closes #889
The inclusions in `basicTrackGroupInclude` keeps growing. I don't know if that's a problem.
=> Add artist name to zip

client/package.json, client/src/components/Artist/ArtistLinks.tsx, client/src/components/ManageArtist/ArtistFormLinks.tsx, client/src/components/ManageArtist/ArtistLinksInHeader.tsx, client/src/components/common/LinkIconDisplay.test.tsx, client/src/components/common/LinkIconDisplay.tsx, client/src/types/index.d.ts, yarn.lock
- Instead of using "Website" for unknown domains, parse the name from the domain (e.g example.com becomes "Example")
- Add more icons based on a selection of sites that different artists have linked to
- Sort link types in "Edit links" dialog
- Add Link interface
=> Further improvements to link display

client/src/components/ManageArtist/CustomizeLook.tsx, client/src/components/ManageArtist/EditTrackRow.tsx, client/src/components/ManageArtist/ManageArtistSubscriptionTiers.tsx, client/src/components/ManageArtist/PostForm.tsx, client/src/components/Merch/ArtistMerchListItem.tsx, client/src/components/Merch/BuyMerchItem.tsx, client/src/components/TrackGroup/TrackGroupMerchItem.tsx, client/src/components/common/LogInForm.tsx, client/src/queries/users.ts, client/src/translation/en.json, src/auth/passport.ts, src/index.ts, src/jobs/send-notification-email.ts, src/queues/album-queue.ts, src/routers/auth/signup.ts, src/routers/v1/trackGroups/{id}/redeemCode.ts, src/routers/v1/users/{userId}/purchases.ts, src/utils/error.ts, src/utils/merch.ts, src/utils/tracks.ts, test/auth/signup.spec.ts, test/routers/trackGroups/{id}.redeemCode.spec.ts
Cleaning up some logging, as well as better error handling in signup.
=> Error handling in auth signup

client/src/components/Admin/CallServerTasks.tsx, src/jobs/optimize-image.ts, src/jobs/queue-worker.ts, src/queues/moving-files-to-backblaze.ts, src/routers/v1/admin/tasks.ts
=> feat: queue and job for moving files from minio to backblaze

client/src/components/Artist/ArtistContainer.tsx, client/src/components/ManageArtist/BulkTrackUpload.tsx, client/src/components/ManageArtist/DeleteArtist.tsx, client/src/components/ManageArtist/ManageArtist.tsx, client/src/components/ManageArtist/ManageTrackGroup.tsx, client/src/components/ManageArtist/ManageTrackRow.tsx, client/src/components/ManageArtist/Posts/PostForm.tsx, client/src/components/ManageArtist/utils.ts, client/src/components/Merch/BuyMerchItem.tsx, client/src/components/TrackGroup/TrackGroup.tsx, client/src/components/Widget/TrackWidget.tsx, client/src/components/common/ImageWithPlaceholder.tsx, client/src/components/common/SmallTileDetails.tsx, client/src/components/common/Tabs.tsx, client/src/components/common/TextEditor/InsertMirloWidgetButton.tsx, client/src/components/common/TextEditor/TopToolbar.tsx, client/src/components/common/TextEditor/index.tsx, client/src/components/common/TrackTable/PublicTrackGroupListing.tsx, client/src/translation/en.json, client/src/types/index.d.ts, prisma/migrations/20250128235105_add_is_drafts_table/migration.sql, prisma/schema.prisma, src/index.ts, src/routers/v1/manage/artists/{artistId}/drafts.ts, src/routers/v1/manage/artists/{artistId}/trackGroups.ts, src/routers/v1/tracks/{id}/index.ts, src/utils/artist.ts, src/utils/minio.ts, src/utils/trackGroup.ts
=> fix: upload preview song

client/src/components/Post/PostCard.tsx
=> Fixed width with ellipsis for long titles to avoid overflow

client/src/components/common/DownloadAlbumButton.tsx, client/src/services/APIInstance.ts
=> Replace download button with a link, to avoid popup blocker problems

Dockerfile, src/jobs/upload-audio.ts
This partially reverts commit 60b4a2d565898494296a9519af4430592c05f6e3
ffmpeg version is floating, probably want to pin it
=> Revert to apt ffmpeg and use libmp3lame codec for upload

client/src/components/Post/PostHeader.tsx, client/src/components/common/FollowArtist.tsx, client/src/types/index.d.ts, prisma/schema.prisma, src/parseIndex.ts, src/routers/v1/manage/posts/{postId}/index.ts, src/routers/v1/posts/index.ts, src/routers/v1/posts/{id}.ts
=> Post Player

client/src/components/ManageArtist/ManageArtistDetails/CustomizeLook.tsx, client/src/components/ManageArtist/ManageTrackGroup/AlbumFormComponents/AllowAllTracksForPromo.tsx, client/src/components/ManageArtist/ManageTrackGroup/AlbumFormComponents/ClickToEditInput.tsx, client/src/components/ManageArtist/ManageTrackGroup/AlbumFormComponents/EditTrackRow.tsx, client/src/components/ManageArtist/ManageTrackGroup/AlbumFormComponents/SavingInput.tsx, client/src/components/ManageArtist/ManageTrackGroup/ManageTrackGroup.tsx, client/src/components/ManageArtist/Merch/MerchForm.tsx, client/src/components/Merch/ArtistMerchListItem.tsx, client/src/components/pages/About.tsx, client/src/translation/en.json, client/src/types/index.d.ts, client/src/utils/artist.ts, prisma/migrations/20250526193609_add_mirlo_promo_boolean_to_tracks/migration.sql, prisma/migrations/20250526201116_add_merch_url_slug/migration.sql, prisma/schema.prisma, src/routers/v1/manage/merch/{merchId}/index.ts, src/routers/v1/manage/tracks/{trackId}/index.ts, src/routers/v1/merch/{id}/index.ts
=> merch urlSlug

client/src/translation/en.json
-preferred "artist page" to "artist" when refering to an artist page on mirlo
-typo in <br />
=> Typos and wording

src/routers/v1/tracks/index.ts
- Tracks returned from the get all tracks db query will have their trackGroups' cover field attached
=> Attach trackGroup -> cover field to Each Track in db query

client/src/translation/en.json
=> "product" to "project"

client/src/translation/en.json
went ahead and added that little flair to this sentence :) solves #1206
=> Patron of the art !

client/src/translation/en.json
=> clarification on notArtistName

docs/Verbal communication guidelines (words we choose and why).md
Added communication guidelines doc. hurray !
Not sure if this is the right place to put this doc. The name might be subject to change if there is a naming convention i'm not aware of (although i like the "words we choose and why" bit).
=> Create Verbal communication guidelines (words we choose and why).md

client/src/components/ManageArtist/ManageSubscriptionTierBox.tsx
=> Bug: Edit subscription tier modal focus

client/src/translation/en.json
I opted to create a "mobileApp" section with the appropriate sub-sections nested inside. Let me know if that sounds like a proper approach.
=> Translations for Mobile

src/jobs/generate-album.ts, src/routers/v1/trackGroups/{id}/download.ts, src/utils/tracks.ts
I am not able to test this, because I don't really want to setup a server but this provides 3 fixes to the audio processing pipeline that should enable unicode support
If you have questions about my recommended changes, let me know
=> Support for unicode characters in titles of tracks and albums

emails/album-purchase-link/subject.pug, src/routers/v1/trackGroups/{id}/emailPurchaseLink.ts
sendMail previously didn't have 'await' in front of it.
=> Fix Email Locals

docs/Verbal communication guidelines (words we choose and why).md
integrated a citation as an integral point of the doc and fixed a typo
=> slight changes to Verbal CommGuidelines doc

README.md, b2-cors-rules.json, client/src/components/ManageArtist/ManageTrackGroup/BulkTrackUpload.tsx, docs/FileStorage.md, minio/Dockerfile, minio/README.md, minio/entrypoint.sh, package.json, src/queues/processTrackAudio.ts, src/routers/v1/manage/tracks/index.ts, src/routers/v1/manage/tracks/{trackId}/process.ts, src/routes.ts, src/utils/minio.ts, yarn.lock
=> fix: signed urls for direct upload to backblaze

client/src/components/CanCreateArtists.tsx, client/src/components/Header/Menu.tsx, client/src/components/Home/Announcement.tsx, client/src/components/ManageArtist/Manage.tsx, client/src/components/Profile/ProfileForm.tsx, client/src/components/Profile/index.tsx, client/src/routes.tsx, client/src/types/index.d.ts, emails/announce-monthly-income-report/html.pug, emails/announce-monthly-income-report/subject.pug, prisma/migrations/20250918220323_add_storing_of_processor_fee_and_platform_cut/migration.sql, prisma/schema.prisma, src/auth/passport.ts, src/jobs/every-month-tasks.ts, src/jobs/send-out-monthy-income-report.ts, src/routers/auth/profile.ts, src/routers/v1/artists/{id}/supporters.ts, src/routers/v1/settings/{setting}.ts, src/utils/stripe.ts, src/utils/subscription.ts, test/jobs/send-out-monthly-income-report.spec.ts, test/routers/manage/artists/index.spec.ts, test/utils.ts, test/utils/subscription.spec.ts
=> Monthly report email 

client/src/components/ManageArtist/ManageArtistDetails/ColorInput.tsx
proposal to fix UX when changing artist page colors, replaced HEX input by native color picker, keeps all functionalities on updating via API and realtime update.
#779 
Current implementation:
My proposal:
Let me know what you think!
=> replace input HEX with color picker

client/src/components/Header/HeaderSearch.tsx
moved tag results to first position
=> set tag result first

client/src/components/ManageArtist/Posts/EditPostHeader.tsx, client/src/components/common/TextEditor/index.tsx
set sticky behaviour with height taken from EditPostHeader component
=> modify text editor toolbar behaviour

client/src/components/common/TextEditor/FloatingLinkToolbar.tsx
=> fix jump when insert url

client/src/components/Home/Home.tsx, client/src/components/Home/NewsletterSignup.tsx, client/src/components/common/EmailVerification.tsx, client/src/translation/en.json
Just some order and minor tweaks to the newsletter sign-up.
=> fix: re-ordering of styles on newsletter
