.husky/pre-commit, .pre-commit-config.yaml, package.json, yarn.lock
I'm partial to using [pre-commit](https://pre-commit.com) as mentioned in https://github.com/funmusicplace/mirlo/issues/101 
Currently, I've disabled the husky pre-commit that runs `yarn test` as the tests were failing on my machine (which would not allow me to commit). Let me know if I've done something wrong. I only ran `yarn` to grab all the dependencies. 
In order to to ensure that husky runs `yarn test` before commit, we can un-comment the last line in `.husky/pre-commit` 
I have not used Commitizen before but [this](https://github.com/commitizen/cz-cli/issues/801) issue is where I've copied the pre-commit config from. It appears to be working?
=> feat: add husky and commitizen through pre-commit

README.md
These are the steps used to fix the "error relocating" errors seen when attempting to run docker with an apple chip. big up to timglorioso for the lead
=> Updated the Readme with a solution to apple chip errors w/ docker

client/src/components/common/PageHeader.tsx
There was previously an issue where if the banner width was below 2500px it could render up to full viewport height depending on its ratio, in smartphone view.
=> Fixed banner height being eratic on smartphone view based on img width.

client/src/components/Artist/ArtistSupport.tsx, client/src/components/Artist/ArtistSupportBox.tsx, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Home.tsx, client/src/components/ManageArtist/Manage.tsx, client/src/components/Player.tsx, client/src/components/Profile/index.tsx, client/src/components/Releases.tsx, client/src/components/common/MarkdownWrapper.tsx, client/src/components/common/PauseButton.tsx, client/src/components/common/PlayButton.tsx, client/src/components/common/TrackRow.tsx, client/src/components/common/TrackRowPlayControl.tsx
Fixes to : 
- Headings (for consistency and readability, titles in FAQ / About / Profile and / Manage sections needed to be more proeminent.
- Only notable difference is "latest release" where I felt the albums needed to be the star of the page vs the title that felt too big and took too much space from the music itself.
- Support boxes are now displayed as "cards" in column, allowing to see them all in one quick glance.
- Replaced "underline" for artists on trackgroups with smaller bold fonts, again to let the artworks shine more while retaining a small differenciation between album name (bigger and normal font) and artist name.
- Play/Pause on track rows caused a little glitch where the name of the track would shift to the side due to inconsistent width with track number.
=> Various Little Fixes

client/src/components/Home.tsx, client/src/components/Login.tsx
When the translation was too long (.ie french) it stuck things on top on home page, and on login it just was on top. Freed up space there so it's slightly more centered.
=> adding some padding on top to free up space on smartphone

client/src/components/Header/Header.tsx
Banner didn't display correctly on page load (it acted as a normal header)
=> fix to banner display on mobile view page load

client/src/components/ManageArtist/TrackGroupCard.tsx, client/src/components/common/Table.tsx
Two minor fixes in mobile view, trackgroup card didn't keep aspect ratio for album images and the tables for supporters were overflowing the main screen.
=> Minor fixes

client/src/components/Artist/ArtistSupportBox.tsx
Noted that when minimum is 0 the "% of this sub" isn't displayed, so I added padding to avoid the support button to be too close to the edge of the box.
=> added padding for support box for when minimum is 0

client/src/components/Artist/ArtistHeaderDescription.tsx, client/src/components/ManageArtist/ManageArtistContainer.tsx, client/src/components/Post/index.tsx, client/src/components/common/PostCard.tsx
Postcards now display normal text on mobile allowing smaller posts to take full advantage of the height.
Margin-top is no longer way too high when user is logged off on artist profiles
"read more" has a slight gradient indicating there's more to read instead of a cut
Follow button on artist post is centered with artist name
=> Minor UI adjustments

client/src/components/Artist/ArtistHeaderDescription.tsx, client/src/components/common/MarkdownWrapper.tsx
H1 was cut because 3rem was half of a line, now it's 2rem on mobile 4rem on desktop allowing for either 1 line of H1 title or 2 lines of normal text, which works better in most situations.
=> Reduced max-height to fit H1 line-height

client/src/components/Artist/ArtistContainer.tsx, client/src/components/ManageArtist/TrackGroupCard.tsx, client/src/components/common/ArtistHeaderSection.tsx, client/src/components/common/Button.tsx, client/src/translation/en.json
Moved "Edit Artist Page" button out of the body, so that you can view your page much closer to what it will look like to viewer, and also so that the "Edit Page" button is visible at all time when you're on your own page.
=> Edit artist page refactor

client/src/components/ManageArtist/ManagePost.tsx
While editing a post on `/manage/artists/1/post/1`, the URL for the `View live` button previously went to `/post/:id`. It has been changed to link to `/:artistSlug/posts/:id`.
NOTE: I noticed that the manage posts page for artists (`/manage/artists/1/posts`) has the same issue. Should that be updated as well?
=> #655 - Fix view live post URL for Artist

client/src/components/ManageArtist/ManagePost.tsx
This PR addresses comments from #658. It uses the `getPostURLReference` utility to get the live preview URL for managing posts, to maintain more consistency across the codebase, rather than accessing the slug and building the URL directly.
=> #655 - Use artist post reference utility for live preview URL

client/src/components/ManageArtist/ManageArtistPosts.tsx
This PR updates the URL on the Manage Artist Posts page to match how the URL is being formed elsewhere, with the `getPostURLReference` utility.
Ref: https://github.com/funmusicplace/mirlo/issues/655#issuecomment-2043529690
=> 655 - Use post URL utility on Manage Artist Posts page

client/src/components/Admin/Users.tsx, client/src/components/Artist/ArtistAlbums.tsx, client/src/components/Artist/ArtistContainer.tsx, client/src/components/Home/Features.tsx, client/src/components/Home/HomeFeatures.tsx, client/src/components/Home/Splash.tsx, client/src/components/Home/SupportMirlo.tsx, client/src/components/ManageArtist/Manage.tsx, client/src/components/ManageArtist/ManageArtist.tsx, client/src/components/ManageArtist/ManageArtistAlbums.tsx, client/src/components/ManageArtist/ManageArtistPosts.tsx, client/src/components/ManageArtist/ManageArtistSubscriptionTiers.tsx, client/src/components/ManageArtist/ManagePost.tsx, client/src/components/ManageArtist/PublishButton.tsx, client/src/components/ManageArtist/TrackGroupCard.tsx, client/src/components/ManageArtist/Welcome.tsx, client/src/components/Post/index.tsx, client/src/components/Profile/index.tsx, client/src/components/common/Button.tsx, client/vite.config.ts
Many links on the site use a  `<Link> <Button /> </Link>` structure, which renders a styled `<button>` element wrapped with an `<a href="...">` from react-router.
When using keyboard navigation, the inner `<button>` element is also focusable and announced to screen readers, even though it does not have any effect when used.
This PR flattens these components into one `<ButtonLink>`, which renders a single `<a>` element with the button styling.
=> Flatten buttons wrapped with links into a single element

Dockerfile, client/index.html
This hopefully fixes an issue with libfdk_aac not existing in the debian `ffmpeg` binary by copying it from an Ubuntu build of `jrottenberg/ffmpeg` and installing libavdevice59 (a dependency that does not appear to get copied correctly).
This also adds an unrelated fix to `client/index.html` for for an issue that prevented the album upload pages from loading in Vite's dev mode (this does not occur in the built site - possibly thanks to Rollup).
=> Copy ffmpeg with libfdk_aac from jrottenberg/ffmpeg

docker-compose.api.yml
This removes `FATAL:  role "root" does not exist` warnings printed in the postgres logs due to its healthcheck script not knowing the configured user.
=> Fix postgres healthcheck-related warnings

client/src/components/ManageArtist/ArtistFormLinks.tsx, client/src/components/ManageArtist/ArtistFormLinksView.tsx, client/src/components/common/LinkIconDisplay.test.tsx, client/src/components/common/LinkIconDisplay.tsx
This uses the simplified [email regex](https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type%3Demail)) used by browsers for input `type=email` validation for an `isEmailLink` function - modified to remove the ability for a `/` to occur before the `@` symbol.
This validation ensures that any link can be explicitly defined as an email or a link by prefixing either `https://` or `mailto:`. If a link does not have the mailto prefix and includes a `/` before an `@` symbol is encountered, then it is treated as a URL.
=> Avoid treating links with @ symbols as an email

client/src/components/common/Button.tsx
This reverts a change in #699 which was an attempt at avoiding an error from styled-components passing unknown props into the react-router `<Link>` component. However, this change resulted in *no* props being passed to the `<Link>` component, which prevents them from working.
=> Fix button links not being clickable

client/src/components/Artist/ArtistContainer.tsx, client/src/components/Artist/ArtistPosts.tsx, client/src/components/Home/Splash.tsx, client/src/components/ManageArtist/ManageArtistContainer.tsx, client/src/components/ManageArtist/ManagePost.tsx, client/src/components/common/Button.tsx, client/src/components/common/ClickToPlay.tsx, client/src/components/common/LoopButton.tsx, client/src/styles.ts
- Fixes `<Button>` style props being passed through to react-router's `<Link>` component
* `@emotion/styled` does have the ability to filter out style props from its components, but it doesn't appear to support this when `as={Link}` is used with a component. As a workaround, I've just implemented [the behavior of react-router's `<Link>`](https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L931) inside of `<ButtonLink>` and used `as="a"` instead.
- Removes unintentional underlines on `<ButtonLink>` components
- Fixes the homepage "Support mirlo" button inheriting a transparent background on light mode
- Fixes the `.buttonRole` style prop not being applied.
* It seems like the previous implementation set both `color` and `background-color` to the same …
=> Misc button-related improvements

client/package.json, client/vite.config.ts, yarn.lock
This configures [@emotion/babel-plugin](https://emotion.sh/docs/@emotion/babel-plugin) in Vite, which primarily minifies the CSS styles - saving a few kbs. However, it also generates source maps for the embedded CSS in dev mode, so that they show up in browser dev tools. It also enables support for [using a component as a CSS selector](https://emotion.sh/docs/styled#targeting-another-emotion-component).
=> Add @emotion/babel-plugin for style minification and source maps

docker-compose.test.yml, test/README.md
This adds configuration for watching the test dir to automatically rebuild the test containers when changes are made.
With this, `docker compose --profile=test watch` will also pick up changes in the `./test` directory and rerun tests when they occur.
=> Add configuration for `docker compose --profile=test watch`

client/src/components/ManageArtist/ArtistFormLinksView.tsx
It will help avoid breaking the music playing when clicking on it
=> Artists links now open in a new tab

client/src/components/Artist/ArtistSquare.tsx, client/src/components/Player/PlayingTrackDetails.tsx, client/src/components/common/ClickToPlay.tsx, client/src/components/common/ClickToPlayAlbum.tsx, client/src/components/common/ImageWithPlaceholder.tsx, src/static.ts
- Prevents the double image fetching in `<ImageWithPlaceholder>`
* Since these requests were not cached, this was adding to the API ratelimit when clicking through release pages
- Ensures that image styling is square in release list & player (related: #520)
* This uses `object-fit: contain;` rather than cropping the image, to ensure that the entire image is visible
* Added lazy loading (which helps when images are out of view, although it *doesn't* help when they're already visible on the page - so it might be good to add a condition to this later)
* Also added a fade-in transition when the image loads 
- Adds `Cache-Control` and `Etag` headers to responses from the `/images` endpoint
* Also added naive support for `If-None-Match`, used with `stale-while-revalidate`
=> Album image styling & cache-control headers

client/src/components/Artist/Artist.tsx, client/src/components/Artist/ArtistPosts.tsx, client/src/components/Artist/ArtistSupport.tsx, client/src/components/Artist/ArtistTrackGroup.tsx, client/src/components/Home/Home.tsx, client/src/components/Home/HomeReleases.tsx, client/src/components/Home/Posts.tsx, client/src/components/ManageArtist/ArtistFormLinksView.tsx, client/src/components/ManageArtist/ManageArtistContainer.tsx, client/src/components/Post/PostCard.tsx, client/src/components/Post/PostGrid.tsx, client/src/components/Releases.tsx, client/src/components/common/Overlay.tsx, client/src/components/common/PostCard.tsx, client/src/components/common/Tabs.tsx, client/src/styles.ts, client/src/utils/getHtmlExcerpt.ts, client/src/utils/useLinkContainer.ts
This PR makes a few changes to post cards:
- Removes the wrapping `<a>` tag, and replaces it with `useLinkContainer` to handle click events
* These mimic the behavior of a link for ctrl+click, middle click, and other mouse interactions, without actually involving an `<a>` element (which otherwise involves working with z-index, and prevents text selection from working as expected)
* This is mostly reused from [unicorn-utterances/href-container-script.ts](https://github.com/unicorn-utterances/unicorn-utterances/blob/main/src/utils/href-container-script.ts)
- Moved some shared structure between the artist "Updates" page and homepage into the `<PostCard>` component
* Consequently, the styling of the post cards in these locations is now the same.
- Added a `getHtmlExcerpt` utility to roughly …
=> Post card a11y and excerpt changes

client/src/components/ManageArtist/AlbumFormComponents/AlbumFormContent.tsx, client/src/components/ManageArtist/ArtistForm.tsx, client/src/components/ManageArtist/ArtistFormColors.tsx, client/src/components/ManageArtist/UploadArtistImage.tsx, client/src/components/ManageArtist/UploadImage.tsx, client/src/components/ManageArtist/Welcome.tsx, client/src/components/common/AutoComplete.tsx, client/src/components/common/Input.tsx, client/src/components/common/Modal.tsx, client/src/translation/en.json
I could have used directly "image type", but two limitations prompted me to create a new variable : 
- Incapacity to customize "a / an" based on the word type ("a background" "an avatar")
- Background is still defined as Banner in the backend, which is something we need to fix but is NOT a trivial rewrite because it's pretty much everywhere in the codebase and could have broken a lot of things. 
New behavior :
=> New variable to customize upload prompt description per image type

client/src/components/pages/About.tsx, client/src/translation/en.json
Fixes #758 
also handles a piece of #759 but the FAQ is kind of a different project.
=> Fix #758 missing about token

Dockerfile
Addresses the warning:
```sh
WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
```
=> From as casing does not match

client/src/components/ManageArtist/utils.ts
The numbering didn't consider already uploaded files when calculating order.
Closes #728
=> Fix track numbering when uploading one at a time.

client/src/state/GlobalState.tsx
When reaching the end, the player will pause, but stay open 
Closes #823
=> Keep player open when last track in queue ends

client/src/components/Artist/ArtistLinks.tsx, client/src/components/ManageArtist/ArtistLinksInHeader.tsx, client/src/components/common/LinkIconDisplay.test.tsx, client/src/components/common/LinkIconDisplay.tsx
I noticed some weirdness with the displayed links on the artist page: 
I cleaned this up, to use the link type that's stored in the database as link title. A further improvement would be to add a possibility to choose "Other" and type the link name in the the "Edit links" dialog. But that's an exercise left for another time.
=> Fix link display

.gitignore, docker-compose.test.yml, src/routers/v1/artists/{id}/subscribe.ts, src/utils/stripe.ts, test/routers/artists/{id}.subscribe.spec.ts
I had to change from `res.status(...)` to `ApiError` for errors. The tests would just hang, waiting for the call to return before I did the change.
=> Add API tests for artist/id/subscribe using stripe-mock

package.json, src/jobs/optimize-image.ts, yarn.lock
Fixes #330 and supersedes #912
Adds [sharp-ico](https://github.com/ssnangua/sharp-ico) package, using that library to create the artist favicon from the artist avatar
Re-doing the changes from the [original PR](https://github.com/funmusicplace/mirlo/pull/912) adding the ability to create a favicon from an artist's avatar.
Somehow `faker` got upgraded and made tests fail.
=> feat: Create a favicon for an artist based on their avatar

client/src/components/ManageArtist/UploadArtistImage.tsx, client/src/components/common/DownloadAlbumButton.tsx, client/src/utils/useJobStatusCheck.ts, package.json, src/config/sharp.ts, src/jobs/optimize-image.ts, src/queues/processImages.ts, src/routers/v1/jobs/index.ts, src/static.ts, src/utils/minio.ts, yarn.lock
This is a punt that switches to using backblaze for images
=> WIP: switch to using backblaze for images

.github/workflows/api-tests.yml
Fixing failures on tests running in GitHub Actions due to updated ubuntu 24.04 runner.
[Failing builds](https://github.com/funmusicplace/mirlo/actions/runs/15586673755/job/43895607254?pr=1237)
[Related Issue on runner-images repo](https://github.com/actions/runner-images/issues/12289)
=> Fix failing tests in CI

client/src/components/ManageArtist/ManageTrackGroup/AlbumFormComponents/EditTrackRow.tsx
Running into `formData.trackFile` undefined, track appears to not save due to lack of toast.
After I named this branch, I noticed it happens even if release isn't published.
=> Bug: Track appears unsaved

client/src/translation/en.json
i did a thing ! i saw this happening from the artist page and thought this might be quite easy to fix so i dipped my toes. i hope it's fixed ?
=> fix: delete confirmation popup showing raw variable name

client/src/components/ManageArtist/ArtistFormLinks.tsx, client/src/components/common/LinkIconDisplay.tsx
**Description:**
This PR addresses issue #1406 by adding TikTok as a new social media link option to the list of available links. It also includes the removal of the `linkUrlDisplay` function from `ArtistFormLinks`, which is no longer needed.
**Changes:**
- Adds a new `tiktok` option to the list of available links.
- Deletes the `linkUrlDisplay` function to clean up the codebase.
**Related Issue:**
Closes #1406
=> feat: Add TikTok to link list and remove unneeded function

client/src/components/Artist/ArtistItemLink.tsx, client/src/components/common/ClickToPlay.tsx
Changes:
- Treated single-track releases as tracks when determining the ClickToPlay overlay label and destination, ensuring hover text says “Go to track” for one-track albums.
- Adjusted ArtistItemLink aria-label generation so track destinations use the “Go to track” phrasing for both tracks and single-track releases.
Why?
- Closes #1277
=> Adjust single-track hover labels

client/src/components/ManageArtist/ManageArtistDetails/CustomizeLook.tsx, client/src/translation/en.json
Changes:
- Added helper text below the tile background image checkbox to clarify how tiling affects the artist banner display.
- Added a corresponding translation string explaining that the background image will repeat to fill the entire area.
Why?
- Closes #1377
=> Add help text for tiling background image option

client/src/components/common/SmallTileDetails.tsx, client/src/translation/en.json
Changes:
- Localized the SmallTileDetails subtitle and footer using `Trans`, so translators can control the full “from/by” phrases shown with release metadata.
- Added English translation templates for the SmallTileDetails subtitle and footer strings to support localization work.
=> Localize SmallTileDetails labels

client/src/components/Checkout/CheckoutError.tsx, client/src/routes.tsx, client/src/translation/en.json, src/routers/v1/checkout/index.ts, src/utils/stripe.ts
Changes:
- Redirected cancelled Stripe checkout requests to a frontend error page, using client and artist lookups to choose the appropriate destination and providing a reason code for display.
- Added client and artist identifiers to Stripe cancel URLs for catalogue purchases, tips, and subscriptions so the API can generate accurate redirects after a cancellation.
- Created a checkout error view with routing and translations to explain cancelled purchases to users on both artist-specific and global pages.
Why?
- Fixes #907
=> Handle cancelled Stripe checkout redirects

client/src/components/ManageArtist/ArtistFormLinks.tsx, client/src/components/common/LinkIconDisplay.tsx, client/src/types/index.d.ts
Changes:
- Enhanced the Manage Artist links form to normalize saved data, fetch DuckDuckGo favicons for custom website entries, and surface the icon previews throughout the editor and link list views.
- Updated the link icon resolver to render stored favicon images and added an optional `iconUrl` property to the shared `Link` type.
Why?
- Closes #930
=> Fetch favicons for custom artist links
